// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcQ1-WgW0a0NqsLmt3-JdPKS5h8-WULGs',
    appId: '1:832371838501:web:f8e70f959313044a0fb9cc',
    messagingSenderId: '832371838501',
    projectId: 'visualaid-78598',
    authDomain: 'visualaid-78598.firebaseapp.com',
    storageBucket: 'visualaid-78598.appspot.com',
    measurementId: 'G-GEEVYTK8EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhgT1VjnvZmJ2QfvVu4QL0K_ffkBmji28',
    appId: '1:832371838501:android:94224a36bb6639d40fb9cc',
    messagingSenderId: '832371838501',
    projectId: 'visualaid-78598',
    storageBucket: 'visualaid-78598.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWEqN6WrSqEmzsn9RcLwBr2MCJFBoQnNc',
    appId: '1:832371838501:ios:ce5420646b5725680fb9cc',
    messagingSenderId: '832371838501',
    projectId: 'visualaid-78598',
    storageBucket: 'visualaid-78598.appspot.com',
    androidClientId: '832371838501-43ji1fme097onqb1jclr22i42a3ihdhf.apps.googleusercontent.com',
    iosClientId: '832371838501-e46abpoogka9tbkmmolavrogov5an790.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWEqN6WrSqEmzsn9RcLwBr2MCJFBoQnNc',
    appId: '1:832371838501:ios:ce5420646b5725680fb9cc',
    messagingSenderId: '832371838501',
    projectId: 'visualaid-78598',
    storageBucket: 'visualaid-78598.appspot.com',
    androidClientId: '832371838501-43ji1fme097onqb1jclr22i42a3ihdhf.apps.googleusercontent.com',
    iosClientId: '832371838501-e46abpoogka9tbkmmolavrogov5an790.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcQ1-WgW0a0NqsLmt3-JdPKS5h8-WULGs',
    appId: '1:832371838501:web:09f1cb4207f3db680fb9cc',
    messagingSenderId: '832371838501',
    projectId: 'visualaid-78598',
    authDomain: 'visualaid-78598.firebaseapp.com',
    storageBucket: 'visualaid-78598.appspot.com',
    measurementId: 'G-DHRMFBMYZN',
  );
}
