// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxiHsHf_dY5Qb35UJBXsDI-xu4_g5Pbog',
    appId: '1:25892591670:web:20738f198b410d56f1a097',
    messagingSenderId: '25892591670',
    projectId: 'visaid-ec3df',
    authDomain: 'visaid-ec3df.firebaseapp.com',
    storageBucket: 'visaid-ec3df.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACWEntPHuB49-Rv2c9RgrEasBN4Pb53x4',
    appId: '1:25892591670:android:cf12a9453ece5716f1a097',
    messagingSenderId: '25892591670',
    projectId: 'visaid-ec3df',
    storageBucket: 'visaid-ec3df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpUcYeRF9vst1ooucETfiLLNNTIYrgTHM',
    appId: '1:25892591670:ios:1e8760f851152827f1a097',
    messagingSenderId: '25892591670',
    projectId: 'visaid-ec3df',
    storageBucket: 'visaid-ec3df.appspot.com',
    androidClientId: '25892591670-pug5s2n1ucgab2479365u8eummd61d0g.apps.googleusercontent.com',
    iosClientId: '25892591670-u47841nclejp6jscnogencka96qn3nqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpUcYeRF9vst1ooucETfiLLNNTIYrgTHM',
    appId: '1:25892591670:ios:1e8760f851152827f1a097',
    messagingSenderId: '25892591670',
    projectId: 'visaid-ec3df',
    storageBucket: 'visaid-ec3df.appspot.com',
    androidClientId: '25892591670-pug5s2n1ucgab2479365u8eummd61d0g.apps.googleusercontent.com',
    iosClientId: '25892591670-u47841nclejp6jscnogencka96qn3nqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxiHsHf_dY5Qb35UJBXsDI-xu4_g5Pbog',
    appId: '1:25892591670:web:95cf79bb2b96b07ff1a097',
    messagingSenderId: '25892591670',
    projectId: 'visaid-ec3df',
    authDomain: 'visaid-ec3df.firebaseapp.com',
    storageBucket: 'visaid-ec3df.appspot.com',
  );

}